spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/lasono
    username: postgres
    password: lasono
    driver-class-name: org.postgresql.Driver
  
  flyway:
    enabled: true