spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/lasono
    username: lasono
    password: lasono
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true